# SPDX-FileCopyrightText: Andrew Ball <andrew@aball.dev>
# SPDX-License-Identifier: MPL-2.0
name: Deploy code

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    # Uses Infisical to get credentials from internal secret store server and add the secrets to environment 
    - name: Import Secrets
      uses: Infisical/secrets-action@v1.0.13
      with:
        method: "oidc"
        env-slug: "dev"
        project-slug: "github-g0zh"
        identity-id: "1ffe6b17-29ef-47ed-a54c-0912bbe40542"
    - uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      with:
        token: ${{env.NGLBOT}}
    - uses: actions/setup-node@v4
      with:
        node-version: 24
        registry-url: https://registry.npmjs.org/
    - name: build
      run: |
        npm i
        npm run build
        npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{env.NPM}}
