name: Deploy code

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
    - uses: actions/setup-node@v4
      with:
        node-version: 24
        registry-url: https://registry.npmjs.org/
    - name: Import Secrets
      uses: Infisical/secrets-action@v1.0.12
      with:
        method: "oidc"
        env-slug: "dev"
        project-slug: "github-g0zh"
        identity-id: "1ffe6b17-29ef-47ed-a54c-0912bbe40542"
    - name: build
      run: |
        npm i
        npm run build
        npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{env.NPM}}
